### ISSUE TITLE
无法正确编译

### ISSUE THREAD

**Issue by vxhly** [BuptStEve/markdown-it-vuese#8]
**版本**
Version [0.4.0]

**描述一下 bug**

![image](https://user-images.githubusercontent.com/17906558/85970459-1fd2e200-b9fd-11ea-909d-1ea7e7eec0d3.png)

**复现 bug**
复现的步骤：

1. 配置
```js
  markdown: {
    lineNumbers: true,
    extendMarkdown: (md) => {
      md.use(require('markdown-it-vuese'), {
        vueseRe: /<\[vuese-h3\]\((.+)\)/i,
        ruleName: 'vuese-h3',
        useRender: (vueseRender) => {
          const renderRes = vueseRender.render()
          const genMd = key => `### ${key}\n${renderRes[key]}\n`

          return Object.keys(renderRes).map(genMd).join('')
        },
      })
    }
  }
```
2. 看到了错误

Error: Cannot find module '/Users/codeman/working/gitee/eh-ui/node_modules/@vuese/parser/dist/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:328:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:689:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1016:27)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/codeman/working/gitee/eh-ui/node_modules/markdown-it-vuese/dist/index.cjs.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at extendMarkdown (/Users/codeman/working/gitee/eh-ui/docs/.vuepress/config.js:45:14)
    at afterInstantiate (/Users/codeman/.nvm/versions/node/v14.4.0/lib/node_modules/vuepress/node_modules/@vuepress/core/lib/node/createMarkdown.js:23:23)
    at module.exports (/Users/codeman/.nvm/versions/node/v14.4.0/lib/node_modules/vuepress/node_modules/@vuepress/markdown/index.js:124:23)

**Comment by BuptStEve** [comment]
麻烦提供一下复现仓库？

**Comment by BuptStEve** [comment]
咋一看感觉是这个问题，~~重装一下 markdown-it-vuese？~~，等 vuese 发个版吧
https://github.com/vuese/vuese/commit/c740fa5d6dc8efd8302c44eed4fcfa242e21e67b

**Comment by BuptStEve** [comment]
发版了，重装下应该就好了~

**Comment by vxhly** [comment]
可以了，谢谢，我一直以为是我配置错了呢
